### ISSUE TITLE
Enable finer grained control over configuration loading

### ISSUE THREAD

**Issue by mseaton** [mekomsolutions/openmrs-module-initializer#47]
@mks-d needs design discussion, but the below is intended to be iterated upon and discussed.  This may be controversial and there may be much better ideas out there, but I figured it's better out for discussion.

The initial proposal would be to support the existence of a top-level configuration file (eg. ".OpenMRS/configuration/initializer.yml"), which would enable implementations to change the details of configuration loading (eg. include or exclude files from loading, change loading order, choose different Loader implementation, etc).

Some possible scenarios:

1. A solution provider wants to develop a set of configurations to deploy to multiple facilities in a single distribution, but needs a subset of these configurations to be deployed on a site-by-site basis (eg. a small number of global properties, location tags, etc).

2. A solution provider wants to explicitly declare the installable artifacts in a single file with an explicit loading order, to make it clear and obvious what is happening.

3. We want a mechanism that will allow us to add further configuration options in the future (eg. replace a standard Loader with a custom loader, add more sophisticated loading order configs, etc)

Some initial use cases to consider:

1. Enable specifying patterns of files to include and/or exclude:

```
configFilters:
  - type: "include"
    path:  "configuration/common/*"
  - type: "include"
    path:  "configuration/$hostname/*"
```

2. Enable specifying specific files, in a specific order, possibly with custom Loaders or custom directory structures:

```
configFiles:
  - description: "Concepts"
    domain: "metadatasharing"
    files:  ["*/concepts/*.zip"]
    loader:  "EmrApiMdsLoader"

  - description: "Locations"
    domain: "locations"
    files:  ["common/core_locations.csv", "ces/mexico_locations.csv"]
```
